### ISSUE TITLE
issue for install package

### ISSUE THREAD

**Issue by rampara56** [hutx/electron-notification-desktop#1]
Cannot find module 'electron-notfier-desktop'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ram/ins-services/amp-gen/server.js:673:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
I am getting this issue,please help me on this issue.....
"module installed but still i am facing this issue".

**Comment by elujoba** [comment]
Hi. I'm presently using this module in an app and it works fine. Will you try sharing some of your code so I can see if I can help? 

PS: I know it's almost a month ago so you might have solved the issue.
